--TABLODAKÝ VERÝLERÝ GETÝRMEK ÝÇÝN KULLANILIR
SELECT * FROM CUSTOMERS
SELECT ID,CUSTOMERNAME FROM CUSTOMERS

--TABLOYA VERÝ EKLEME
INSERT INTO CUSTOMERS
(CUSTOMERNAME,CITY,BIRTHDATE,DISTRICT,GENDER)
VALUES ('MEHMET ÖZAL','ANTALYA','1990-12-21','ALANYA','E')

USING ETRADE

--TABLODA VERÝ DEÐERÝ DEÐÝÞTÝRME
UPDATE CUSTOMERS SET NATION = 'TR' , AGE = DATEDIFF(YEAR,BIRTHDATE,GETDATE())

--TABLODAN VERÝ SÝLMEK ÝÇÝN KULLANIR
DELETE FROM CUSTOMERS WHERE ID = 1005

--TABLOYU ÝLK OLUÞTURULDUÐU HALÝNE DÖNÜÞTÜRMEK
TRUNCATE TABLE CUSTOMERS

--ÞART ÖRNEKLERÝ
SELECT * FROM CUSTOMERS WHERE CITY = 'ÝZMÝR'
SELECT * FROM CUSTOMERS WHERE CITY <> 'ÝZMÝR'
SELECT * FROM CUSTOMERS WHERE BIRTHDATE < '19980101'
SELECT * FROM CUSTOMERS WHERE BIRTHDATE BETWEEN '19980101' AND '20220101'
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE '%ALÝ%'
SELECT * FROM CUSTOMERS WHERE CITY IN ('ÝZMÝR','ÝSTANBUL')

--AND ve OR OPERATÖRLERÝ
SELECT * FROM CUSTOMERS WHERE CITY = 'ÝSTANBUL' AND DISTRICT = 'BEYLÝKDÜZÜ'
SELECT * FROM CUSTOMERS WHERE CITY = 'ÝSTANBUL' OR CITY = 'ANKARA'

--TEKRAR EDEN KAYITLARI TEKÝLLEÞTÝRMEK
SELECT DISTINCT CITY FROM CUSTOMERS

--VERÝLERÝ SIRALAMAK
SELECT * FROM CUSTOMERS ORDER BY AGE DESC

--SINIRLI SAYIDA VERÝ GETÝRMEK
SELECT TOP 500 * FROM CUSTOMERS