--Aggregate Functions

SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(*), SUM(TOTALPRICE), AVG(TOTALPRICE) FROM SALES  

SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(*), SUM(TOTALPRICE), AVG(TOTALPRICE) FROM SALES  
WHERE CITY = 'ADANA'

--GROUP BY

SELECT 
CITY,
MIN(TOTALPRICE) AS MINPRÝCE, MAX(TOTALPRICE) AS MAXPRICE, COUNT(*) AS _ROWCOUNT, SUM(TOTALPRICE) AS TOTALPRICE, AVG(TOTALPRICE) AS AVGPRICE 
FROM SALES  
GROUP BY CITY

SELECT TOP 10
CITY, SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES  
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC

-- BÝR MAÐAZANIN GÜN BAZLI TOPLAM SATIÞLARI
SELECT CITY,DATE2,SUM(TOTALPRICE)
FROM SALES 
WHERE CITY = 'ANKARA'
GROUP BY CITY,DATE2
ORDER BY CITY,DATE2 DESC

--BÝR GÜNÜN MAÐAZA BAZLI SATIÞ RAKAMLARINI GETÝRME
SELECT DATE2,CITY,SUM(TOTALPRICE) 
FROM SALES
WHERE DATE2 = '2019-12-30'
GROUP BY DATE2,CITY
ORDER BY SUM(TOTALPRICE) DESC

--MAÐAZALARIN AYLARA GÖRE SATIÞ RAKAMLARINI GETÝRME
SELECT CITY,MONTHNAME_,SUM(TOTALPRICE)
FROM SALES 
GROUP BY CITY,MONTHNAME_
ORDER BY CITY,MONTHNAME_ ASC

--ÜRÜN KATEGORÝLERÝNE GÖRE SATIÞ RAKAMLARINI GETÝRME
SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4, SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4 ASC

--MAÐAZALARIN MÜÞTERÝ SAYILARINI GETÝRME
SELECT  CITY,COUNT(DISTINCT FICHENO) AS ROWCOUNT_
FROM SALES
GROUP BY CITY 
ORDER BY CITY ASC

--BELLÝ BÝR CÝRONUN ÜZERÝNDE SATIÞ YAPAN MAÐAZALARI GETÝRME
SELECT CITY, SUM(TOTALPRICE)
FROM SALES
GROUP BY CITY
HAVING SUM(TOTALPRICE)<40000
ORDER BY SUM(TOTALPRICE) DESC



